# Generated by Django 4.0.6 on 2022-08-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='gst_amount',
        ),
    ]
